### PR TITLE
Pull request merged with 0.16 master

### PR DESCRIPTION
**Pull request by hasinitg**
This is the updates pull request of https://github.com/apache/airavata/pull/10 which is merged with the latest Airavata 0.16 master.

### CODE REVIEW

**Comment by smarru** [comment]
Hi Hasini, can you please update this PR with latest code. The merge is failing. Can you do a git pull on your branch, the the PR should get updated.

**Comment by smarru** [comment]
Can you please also move the security properties in airavata-api/airavata-api-server/src/main/java/org/apache/airavata/api/server/security/Properties.java into airavata-server.properties - airavata/modules/configuration/server/src/main/resources/airavata-server.properties?

**Comment by hasinitg** [comment]
Hi Suresh,  Thank you for the comments. Actually,I created this pull request after merging with the latest code. I will send an updated pull request again. 
Regarding airavata-api/airavata-api-server/src/main/java/org/apache/airavata/api/server/security/Properties.java, I have already moved those to airavata-server.properties in the above pull request. That file is not in use, I will remove it in the next pull request.
Thanks,
Hasini.

**Comment by hasinitg** [comment]
Hi Suresh,
I created a new pull request (https://github.com/apache/airavata/pull/13) based on the latest Airavata code. Can you please check if it works?
Thanks,
Hasini.

**Pull request merged**
