### PR TITLE
Adding SSH Credential summary data model

### PR DESCRIPTION
**Pull request by anujbhan**
This feature will help retrieve more information on SSH public keys displayed in gateway Clients.

**Airavata Endpoint affected:**

**New:**
 ```public List<CredentialSummary> getAllGatewaySSHPubKeysSummary(AuthzToken authzToken, String gatewayId)```

 **returns a list of Credential objects :**
            ```struct CredentialSummary {
                                                             1: required string gatewayId,
                                                             2: required string username,
                                                             3: optional string publicKey,
                                                             4: optional i64 persistedTime,
                                                             5: optional string description
                                                            }```

**Note: API level test are pending, will push code soon**

### CODE REVIEW

**Comment by shamrath** [comment]
Hi Anuj 

Followings are few suggestions to improve your pull request. 

1. We can do this in a better way by adding generic API method(to AiravataAPIServer) like "getAllCredentialSummary" instead of adding API method for each credential types eg: "getAllGatewaySSHPubKeysSummary" which will return all the credential summary for that particular gatewayId. You may be able to remove few redundant methods from Airavata API server.
2. Let's introduced one credential summary struct to all credential types, how we differentiate is we have credential type enum field( SSH, PASSWD, CERT etc ) in the credential summary thrift struct. 
3. Move credential data model thrift file to data model directory and merge credential summary thrift file with it. 
4. Credential stubs still have date fields in generated thrift files, not because your changes, but we need to fix it so remove it.

**Comment by smarru** [comment]
Very nice list of improvements. I was penciling some of these for a API review, but good that you are suggesting to get them done now. 

+1 for all 4 suggestions. 

Suresh

**Comment by anujbhan** [comment]
@shamrath,

Indeed a good list of improvements, this way the Airavata Api will remain clutter free. I will start the development on these shortly.

**Comment by anujbhan** [comment]
@smarru,
Method to fetch specific user's public keys with summary is added

**Comment by smarru** [comment]
Can we review and merge this now? I mean are you done working on this PR?

**Comment by anujbhan** [comment]
All the festures requested are there in  this PR. But i am working on the
additional changes prescribed by shameera

On Oct 12, 2016 2:16 PM, "Suresh Marru" <notifications@github.com> wrote:

Can we review and merge this now? I mean are you done working on this PR?

> On Oct 12, 2016, at 1:19 PM, Anuj Bhandar <notifications@github.com>
wrote:
>
> @smarru <https://github.com/smarru>,
> Method to fetch specific user's public keys with summary is added
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <
https://github.com/apache/airavata/pull/54#issuecomment-253278638>, or mute
the thread <https://github.com/notifications/unsubscribe-
auth/ACbXSjo-r85VddHayUhJa-y_SYvfh7oPks5qzRa4gaJpZM4KTEWl>.

>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/apache/airavata/pull/54#issuecomment-253294073>, or mute
the thread

**Comment by anujbhan** [comment]
@smarru & @shamrath,

Optimization to this PR may take some time. Since this PR is critical, Please consider merging. I will submit the changes as soon as possible with another pull request.

The build is passing in my local environment, don't know why Travis is failing.

**Comment by shamrath** [comment]
@anujbhan ,
Ok let's make this an exception. Please create follow up JIRA to track the pending improvements. I will review and merge this.

**Comment by anujbhan** [comment]
@shamrath,

Here is the follow up JIRA : https://issues.apache.org/jira/browse/AIRAVATA-2163, and I have moved the credential store thrift file to data-models directory, though the actual data models will be created in credential-store modules directory.

**Pull request merged**
