### PR TITLE
Added util to airavata-cpp-sdk/../client_samples .

### PR DESCRIPTION
**Pull request by priyanshu-sekhar**
Added util folder inside airavata-cpp-sdk/src/main/resources/client_samples to register applications.
Please read util/README for more details.

### CODE REVIEW

**Comment by smarru** [comment]
Hi Priyanshu, great that you are able to do a PR with the samples. Since your branch is behind the 0.15 branch, I could not merge it. Can you update the branch checkout again and try again?

**Comment by priyanshu-sekhar** [comment]
Sir, in my forked repo it says "This branch is 1 commit ahead of apache:airavata-0.15-release-branch" and comparing changes with the airavata-0.15-release-branch shows that they are "Able to merge" . Can you please verify again.

**Comment by smarru** [comment]
Priyanshu, I still get an error: can you can do a git pull again on origin and let me know:
error: failed to push some refs to 'https://git-wip-us.apache.org/repos/asf/airavata.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by priyanshu-sekhar** [comment]
Sir I did a get pull and cross-checked it with the remote repo (git remote -v update). Please check if you can merge it now. if the error persists, I'll clone the whole repo again and send you a PR

**Comment by priyanshu-sekhar** [comment]
sir did it work?

**Comment by smarru** [comment]
Priyanshu It did not work. Either you can send me a clean PR, or I was planning to copy your additions manually and try it.

**Pull request closed without merging**
