### PR TITLE
[AIRAVATA-2603] Adding/Migrating new and existing group related API methods to profile service module

### PR DESCRIPTION
**Pull request by sachinkariyattin**
- Currently group related API's like createGroup(), updateGroup() etc exist in the airavata-api module. The goal is to migrate these methods to profile-service module.
- Adding API methods for the new group roles methods in the profile-service module. Currently CPIs like addGroupAdmins(), removeGroupAdmins() etc exist in the sharing-registry module.

**Changes**
- Added GroupManagerService inside profile-service module.
- Migrated createGroup(), updateGroup, deleteGroup(), getGroup() and getAllGroupsUserBelongs() API methods from API server to GroupManagerService.
- Also, added the API methods for the new group roles(Owner, Admin, User) CPI's in sharing-registry module. So, the **GroupManagerService** contains the following methods

```
    createGroup()
    updateGroup
    deleteGroup()
    getGroup()
    getAllGroupsUserBelongs()
    transferGroupOwnership()
    addGroupAdmins()
    removeGroupAdmins()
    hasAdminAccess()
    hasOwnerAccess()
```
- Added tests for group roles in `SharingRegistryServiceTest `and `SharingRegistryServerHandlerTest`
- Added `GroupManagerSample (client)`  in profile-service-client-sdks module

### CODE REVIEW

**Comment by sachinkariyattin** [comment]
@smarru  I was creating the Sharing Service client using the org.apache.airavata.api.server.util.ThriftClientPool. Should I just create a regular client instead of using the object pool?

**Comment by smarru** [comment]
@sachinkariyattin the client pool is recommended. For now create a regular client, but after this PR is completed, lets move the client pool to a commons library and use it in all thrift servers. There are quite a few thrift servers which are not using this.

**Comment by smarru** [comment]
@machristie any impressions on this PR?

**Comment by machristie** [comment]
@smarru Looks good to me

**Pull request merged**
