### PR TITLE
Made design changes

### PR DESCRIPTION
**Pull request by ajain13**
I made some design changes to the AuroraJobScheduler.java and added utilities package.

### CODE REVIEW

**Comment by smarru** [comment]
@ajain13 can you change the file structure to follow the standard maven and make sure the maven build works before we can merge this PR. You can use this as a reference or other Airavata modules - https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by ajain13** [comment]
@smarru I used ANT for initial check. I will look at the link right away and also look at other Airavata modules and incorporate it.

**Comment by ajain13** [comment]
@smarru I added the file structure to follow standard maven and maven build works.

**Comment by shamrath** [comment]
Which build tool are you using to build your code?

**Comment by ajain13** [comment]
@shamrath  I am using Maven to build my code.

**Comment by shamrath** [comment]
could you explain the use of modules/cloud/AuroraMarathonIntegration/src/README.md ? 
and also 0.16 is released and you should change your cloud module version to 0.17-SNAPSHOT

**Comment by ajain13** [comment]
@shamrath modules/cloud/AuroraMarathonIntegration/src/README.md file is an old README file which I will get rid off.

**Comment by shamrath** [comment]
Change airavata-cloud parent module version too in your pom.xml, I am just here try to make travis-ci works  fine with your code.

**Comment by ajain13** [comment]
@shamrath So when I change the parent module version, I also have to change the pom.xml of the parent directory and so on right ?

**Comment by ajain13** [comment]
@shamrath Can you tell me what other pom.xml files require the change ? Do I have to make changes in all the pom.xml files all the way till the root folder i.e airavata/pom.xml , airavata/modules/cloud/pom.xml ?

**Comment by shamrath** [comment]
let me change cloud module version for you.

**Comment by shamrath** [comment]
get a git pull now and it will have 0.17-SNAPSHOT.

**Comment by ajain13** [comment]
@shamrath  I have made some design changes in orchestrator. Should I make those changes again after the git pull as none of my changes have been merged yet.

**Comment by shamrath** [comment]
Your local changes preserve with git pull, sometimes you will get conflicts with remote code changes, which you need to fix and commit again. Anyway as a best practice and avoid a lot of merge conflicts it is always good to keep you code sink with the remote repository.

**Comment by ajain13** [comment]
@shamrath  I just did a rebase. I think Travis CI should work now

**Comment by shamrath** [comment]
could you also run git merge airavata:develop and make sure there are no any conflicts? BTW hope your git branch code is sync with airavata git develop branch.

**Comment by ajain13** [comment]
@shamrath Yes, My branch is in sync with airavata git develop branch.

**Pull request closed without merging**
