### PR TITLE
Fixing exception handling of GfacServerHandler

### PR DESCRIPTION
**Pull request by DImuthuUpe**

### CODE REVIEW

**Comment by machristie** [comment]
@DImuthuUpe looks good! Can you make the changes on your develop branch instead, so we can merge this into develop?

**Comment by DImuthuUpe** [comment]
@machristie, this is specific to group-based-auth branch. In develop branch there is no RuntimeException thrown unless you haven't merged group-based-auth to develop. I only have to improve the logs. Shall I do that change or do you expect to merge group-based-auth to develop in future?

**Comment by machristie** [comment]
@DImuthuUpe the RuntimeException change is on the develop branch: https://github.com/apache/airavata/commit/f5aaf3305418c72856f6927556ae78be6398963d. The develop branch was then merged into the group-based-auth branch at a later point in time which is why the RuntimeException change is also on the group-based-auth branch.

The plan is to periodically merge develop into group-based-auth and then eventually, once the group based auth work is done, merge group-based-auth back into develop.  So for now let's fix this on develop branch.

**Comment by DImuthuUpe** [comment]
Closing as this was applied on develop branch

**Pull request closed without merging**
